frr defaults traditional
hostname r11
no ipv6 forwarding
!
password zebra
enable password zebra
!
router isis lab
 net 49.0001.1230.1101.1011.00
 is-type level-2-only
 metric-style wide
 no hostname dynamic
 mpls-te on
 mpls-te router-address 123.11.11.11
exit
!
interface eth1
 ip address 10.10.11.2/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth2
 ip address 10.11.101.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 20
 link-params
  enable
  metric 20
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth3
 ip address 10.11.100.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth4
 ip address 10.1.31.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 20
 link-params
  enable
  metric 20
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface lo
 ip address 123.11.11.11/32
 ip router isis lab
 isis passive
exit
!
