frr defaults traditional
hostname r100
no ipv6 forwarding
!
password zebra
enable password zebra
!
router isis lab
 net 49.0001.1231.2310.0100.00
 is-type level-2-only
 metric-style wide
 no hostname dynamic
 mpls-te on
 mpls-te router-address 123.123.100.100
exit
!
interface eth1
 ip address 123.1.1.100/24
 ip router isis lab
 isis network point-to-point
 isis metric 15
 link-params
  enable
  metric 15
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  srlg 100
 exit-link-params
exit
!
interface eth2
 ip address 10.10.100.2/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  srlg 100
  srlg 300
 exit-link-params
exit
!
interface eth3
 ip address 10.11.100.2/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth4
 ip address 10.13.100.2/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth5
 ip address 10.100.111.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 20
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  srlg 200
 exit-link-params
exit
!
interface eth6
 ip address 10.100.110.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 100
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 5.00e+05
  unrsv-bw 5 5.00e+05
  unrsv-bw 6 5.00e+05
  unrsv-bw 7 5.00e+05
  admin-grp 0x00000004
  srlg 200
 exit-link-params
exit
!
interface eth7
 ip address 10.100.101.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 15
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface lo
 ip address 123.123.100.100/32
 ip router isis lab
 isis passive
exit
!
