frr defaults traditional
hostname r11
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 10.10.11.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth2
 ip address 10.11.101.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.11.100.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth4
 ip address 10.1.31.1/30
 ip ospf 1 area 0
 ip ospf cost 10
exit
!
interface lo
 ip address 123.11.11.11/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 123.11.11.11
exit
!
