frr defaults traditional
hostname r100
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 123.1.1.100/24
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 15
exit
!
interface eth2
 ip address 10.10.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.11.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth4
 ip address 10.13.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth5
 ip address 10.100.111.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth6
 ip address 10.100.110.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth7
 ip address 10.100.101.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.100.100/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 123.123.100.100
exit
!
