frr defaults traditional
hostname r15
no ipv6 forwarding
!
password zebra
enable password zebra
!
router isis lab
 net 49.0001.1230.1501.5015.00
 is-type level-2-only
 metric-style wide
 no hostname dynamic
 mpls-te on
 mpls-te router-address 123.15.15.15
exit
!
interface eth1
 ip address 10.15.111.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  admin-grp 0x00000002
 exit-link-params
exit
!
interface eth2
 ip address 10.15.110.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface lo
 ip address 123.15.15.15/32
 ip router isis lab
 isis passive
exit
!
