frr defaults traditional
hostname r111
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 10.14.111.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth2
 ip address 10.15.111.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.100.111.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth4
 ip address 10.101.111.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth5
 ip address 10.110.111.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.111.111/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 123.123.111.111
exit
!
