frr defaults traditional
hostname r130
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 10.30.130.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth2
 ip address 10.31.130.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.130.131.1/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.30.30/32
 ip ospf 1 area 1
exit
!
router ospf 1
 ospf router-id 123.123.30.30
exit
!
