frr defaults traditional
hostname r131
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 10.30.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth2
 ip address 10.31.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.130.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.31.31/32
 ip ospf 1 area 1
exit
!
router ospf 1
 ospf router-id 123.123.31.31
exit
!
