frr defaults traditional
hostname r10
no ipv6 forwarding
!
password zebra
enable password zebra
!
router isis lab
 net 49.0001.1230.1001.0010.00
 is-type level-2-only
 metric-style wide
 no hostname dynamic
 mpls-te on
 mpls-te router-address 123.10.10.10
exit
!
interface eth1
 ip address 123.1.1.10/24
 ip router isis lab
 isis network point-to-point
 isis metric 15
 link-params
  enable
  metric 15
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  srlg 100
 exit-link-params
exit
!
interface eth2
 ip address 10.10.100.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  srlg 100
  srlg 300
 exit-link-params
exit
!
interface eth3
 ip address 10.10.101.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 35
 link-params
  enable
  metric 35
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
  admin-grp 0x00000002
 exit-link-params
exit
!
interface eth4
 ip address 10.10.11.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 10
 link-params
  enable
  metric 10
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface eth5
 ip address 10.1.30.1/30
 ip router isis lab
 isis network point-to-point
 isis metric 1
 link-params
  enable
  metric 1
  max-bw 1.25e+07
  max-rsv-bw 1.25e+07
  unrsv-bw 0 1.25e+06
  unrsv-bw 1 1.25e+06
  unrsv-bw 2 1.25e+06
  unrsv-bw 3 1.25e+06
  unrsv-bw 4 1.25e+06
  unrsv-bw 5 1.25e+06
  unrsv-bw 6 1.25e+06
  unrsv-bw 7 1.25e+06
 exit-link-params
exit
!
interface lo
 ip address 123.10.10.10/32
 ip router isis lab
 isis passive
exit
!
